### ISSUE TITLE
Left side pixel line on some monitors 

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/UBpi#10]
https://youtu.be/z9qIUUXx8tQ

Some people are reporting single pixel line on the left of monitors. 

Seems to be a flaw in the raspi?

Workaround is adding overscan_right=1 to config.txt.

Is thus available via pibootctl? Wondering if such a checkbox should be available on the display tab.

**Comment by samlane-ma** [comment]
Looking at this, it appears pibootctl doesn't handle this, though we could do something on our own. I am wondering if this is still is even an issue though with the newer kernels. I can't seem to find a definitive "this is fixed", but I haven't personally seen this reoccur in the last couple of releases, and it appears the discussions on this haven't had any new posts in over a year.

i.e.

https://github.com/raspberrypi/linux/issues/4187

https://forums.raspberrypi.com/viewtopic.php?t=308910

**Comment by fossfreedom** [comment]
Yeah. Agree. Let's not worry about it!
