### ISSUE TITLE
Unneeded packages 

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/UBpi#13]
Let's see if we can removed these packages from the build since they are seen when updating for the first time

![20210924_172134](https://user-images.githubusercontent.com/996240/134708702-11a2a1d0-6e14-4dc7-b0c8-497f30ce5996.jpg)

**Comment by samlane-ma** [comment]
Looks like this might be a known issue:
https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1925265

**Comment by samlane-ma** [comment]
From initial test it seems this can be fixed in /usr/sbin/oem-config-remove-gtk by changing:

```
def _on_transaction(trans):
    apt_dialog = AptProgressDialog(trans)
    ...
```
to:
```
def _on_transaction(trans):
    trans.set_remove_obsoleted_depends(remove_obsoleted_depends=True)
    apt_dialog = AptProgressDialog(trans)
    ...
```
Successfully created an image in which `sudo apt autoremove` had nothing to remove.  Going to create another image to double check that this does indeed solve the issue.

**Comment by samlane-ma** [comment]
Commented on the issue on Launchpad.  In the meantime, our script will now add the necessary modification to make sure there are no packages to clean up after the initial setup.

**Comment by samlane-ma** [comment]
Upstream has fixed the issue for Mantic. Tested the latest images and I no longer have these packages to remove by default. I am fairly confident in this fix as its the same "tweak" we have successfully been using for Budgie Kinetic and Lunar images, so seems to me to be resolved.
