### ISSUE TITLE
swap file option

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/UBpi#17]
Raising from here https://discourse.ubuntubudgie.org/t/testing-22-04-are-you-brave-enough/5461/46?u=fossfreedom

Need to keep an eye on this in 22.04 - seems like the at least the 4GB version of the pi needs a swap file to operate.

Question is why - feels like a bug - so needs investigating.

Workarounds - documentation in README and/or software solutions may have to consider as well.

**Comment by samlane-ma** [comment]
Still testing, but I have created an image for 22.04 with the v5.15 kernel.  Currently I am using it on a 4GB model without a swap file, with no issues as of yet.

**Comment by fossfreedom** [comment]
lets close - doesnt appear to be an issue
