### ISSUE TITLE
App tidyup on image

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/UBpi#3]
Reminder to look at the following:

1. GNOME To-Do is installed on the tech preview 2 image - done by removing in the setup file
2. Snap-Store is installed on the tech preview 2 image - dunno why.
3. Need to separate raspi gsettings changes (theme/animation etc) from the arm-desktop package.  This is needed to allow the findmypi stuff to be installed on amd64 (otherwise the arm-desktop package will change the theme/animation on 64bit installs).  - In Progress.

**Comment by fossfreedom** [comment]
Need to check our VNC option - https://launchpad.net/ubuntu/+source/gnome-settings-daemon

Vino (Desktop Sharing) has been dropped -  I haven't seen how the replacement "gnome-remote-desktop" changes things.

**Comment by fossfreedom** [comment]
@samlane-ma bad news - the dropping of the vino patch means there is no longer any GUI (in GNOME Settings) to enable/disable the vnc server called vino

vino is still in to repo - so if we still want to use it we need to 

1. install vino
2. Run `/usr/lib/vino/vnc-server`
3. Optionally enable automatic login (without prompting on the PI) via `gsettings set org.gnome.Vino prompt-enabled true`

The alternative I suppose is to install another vnc-server from the repo and configure.

**Comment by samlane-ma** [comment]
Re: item 2 - still remnants of snap store and other snaps to weed out, notice some [MOUNT] messages on startup / shutdown for the 3 removed snaps

**Comment by fossfreedom** [comment]
Have been talking via IRC to debian with regards to gnome-remote-desktop - need to test some suggested package changes to gnome-remote-desktop - if successful then hopefully debian will then make those changes ... then it will sync to Ubuntu.  Watch this space...

**Comment by fossfreedom** [comment]
We are almost there with the VNC stuff ...

In addition from here https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1911030 - Canonical looks like they are not prioritising the v3d overlay copy into the overlays folder :( 

So we'll have to copy the overlay (if not already there) if the user selected the v3d graphics option.

**Comment by fossfreedom** [comment]
Lets close this - think everything should be resolved now.
