### ISSUE TITLE
Guide what each option offers

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/UBpi#6]
Looking at current videos and comments some people may needs little help to understand what each option offers. E g. GPU memory can improve video playback.

Let's consider if we can give hints to users e.g. tooltips and/or focus updating statusbar.

**Comment by samlane-ma** [comment]
I like the way Window Shuffler does this, could do something similar:

![shuffler](https://user-images.githubusercontent.com/67085765/113497770-fa678d00-94d4-11eb-81c7-e43e617329c2.png)

**Comment by fossfreedom** [comment]
dealt with in 21.10
